name: camel_eval
version: "1.0.0"
profile: camel

model-paths: ["models"]
seed-paths: ["seeds"]

vars:
  raw_parquet_path: "../data/bronze/train.parquet"
  silver_parquet_path: "../data/silver/train_sample.parquet"
  results_jsonl_path: "../results/predictions.jsonl"

models:
  camel_eval:
    bronze:
      +materialized: view
    silver:
      +materialized: table
    gold:
      +materialized: table
      +enabled: "{{ var('enable_gold', false) }}"
